name: Publish image
on:
  push:
    branches: [ main dev ]
  schedule:
    - cron: '05 10 * * *'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # required for arm64 builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # builder that can support multiarch
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: "ghcr.io/shc-astra/rover-basestation"
